[[redirects]]
  from = "https://check.crackedminds.co.uk/*"
  to = "/products/check/:splat"
  status = 200

[[redirects]]
  from = "https://gateway.crackedminds.co.uk/*"
  to = "/gateway/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
